### ISSUE TITLE
--install option is not recognized

### ISSUE THREAD

**Issue by alearq** [JKamsker/JKToolKit.Spectre.AutoCompletion#4]
Hello!

I am completely new to Spectre.Console.Cli and wanted to try out this nice extension. Unfortunately the --install option does not seem to be registered correctly with the latest version of Spectre.Console.Cli
```
Error: Unknown option 'install'.

       completion powershell --install
                             ^^^^^^^^^ Unknown option
```

I took a very quick look at the code and a quick guess is that it might now be required to use this attribute:
```
[CommandOption("--install")]
```

above the Install property in the powershell settings class?

**Comment by JKamsker** [comment]
Yea seems like i have forgotten that. I will add that asap.

**Comment by JKamsker** [comment]
Solved in https://github.com/JKamsker/JKToolKit.Spectre.AutoCompletion/commit/375f5c51e8023a2c207ba1c5679bf21d08bafe61
Thanks for bringing it up!
